# Generated by Django 5.2.6 on 2025-10-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
