# Generated by Django 5.2.6 on 2025-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_api", "0002_alter_currency_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("official_name", models.CharField(max_length=300, unique=True)),
                ("flag", models.URLField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("EUR", "Europe"),
                            ("AME", "Americas"),
                            ("AFR", "Africa"),
                            ("ASI", "Asia"),
                            ("OCE", "Oceania"),
                            ("ANT", "Antarctic"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("ccn3", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="currency",
            name="flag",
        ),
        migrations.AddField(
            model_name="currency",
            name="table",
            field=models.CharField(default="A", max_length=1),
        ),
        migrations.AddField(
            model_name="currency",
            name="countries",
            field=models.ManyToManyField(to="currency_api.country"),
        ),
    ]
