# Generated by Django 5.2.6 on 2025-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_api", "0003_country_remove_currency_flag_currency_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="countries",
            field=models.ManyToManyField(
                related_name="countries", to="currency_api.country"
            ),
        ),
    ]
