# Generated by Django 5.2.6 on 2025-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_api", "0004_alter_currency_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="countries",
            field=models.ManyToManyField(
                related_name="currencies", to="currency_api.country"
            ),
        ),
    ]
