# Generated by Django 5.2.6 on 2025-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency_api", "0006_usercurrencytransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercurrencytransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
